##########



POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email" : "mcoutur@algebra.hr",
    "password" : "eheehe",
    "name" : "Couturier",
    "surname" : "Martin"
}

##########




POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email" : "mcoutur@algebra.hr",
    "password" : "eheehe"
}